import Link from "next/link";
import { Repository } from "models/repository";
import { getRepositories } from "functions/repository";

const login: string = "itsubaki";

// https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export const metadata = {
  title: "next13-training",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const repos: Repository[] = await getRepositories(login);
  repos.sort((a: Repository, b: Repository) => {
    if (a.pushed_at < b.pushed_at) {
      return 1;
    }

    return -1;
  });

  return (
    <html lang="en">
      <body>
        app/layout.tsx
        <div>{children}</div>
        {repos.map((repo) => {
          return (
            <div key={repo.id}>
              <Link href={`/repos/${repo.name}`}>{repo.name}</Link> :{" "}
              {repo.description} {repo.language} {repo.stargazers_count}{" "}
              {repo.forks}
            </div>
          );
        })}
      </body>
    </html>
  );
}
