name: tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3

      - name: Install dependencies
        runs: make install

      - name: Lint
        runs: make lint
